### ISSUE TITLE
OFDM中的OAMP和LASSO

### ISSUE THREAD

**Issue by xb1176989662** [STARainZ/DL-OAMP-for-CP-free#1]
OAMP算法是解决LASSO推理问题，但是LASSO需要信号是稀疏的或者可以变换到稀疏域，但是在SISO-OFDM的OAMP中，信号时域采样点和子载波数量一致，所以变换到频域也依然不稀疏，那这种情况下为什么还能用OAMP呢，希望大佬解惑~

**Comment by STARainZ** [comment]
> OAMP算法是解决LASSO推理问题，但是LASSO需要信号是稀疏的或者可以变换到稀疏域，但是在SISO-OFDM的OAMP中，信号时域采样点和子载波数量一致，所以变换到频域也依然不稀疏，那这种情况下为什么还能用OAMP呢，希望大佬解惑~

Hi Bin Xu,

The OAMP algorithm can also be derived from the message passing perspective/in the Bayes-optimal setting similar to the AMP algorithm. The Bayes-optimal OAMP requires the prior of the signal to be known and applies to non-sparse signals (e.g., the commonly used QAM modulation signals in wireless communications). You can refer to [1] and [2] for details.

[1] J. Ma and L. Ping, “Orthogonal AMP,” IEEE Access, vol. 5, pp. 2020–2033, Jan. 2017.
[2] Q. Zou and H. Yang, “A concise tutorial on approximate message passing,” arXiv preprint arXiv:2201.07487, 2022.

Best regards,
Xingyu Zhou

**Comment by xb1176989662** [comment]
Thank you very much and wish you the best of luck in your research
